# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


pool:  
  vmImage: 'ubuntu-16.04' 
  
trigger: 
    - master
    - azure-pipelines

steps:
  - task: Npm@1
    inputs:
      command: 'install'
  - script:
      npm test
    displayName: 'Run unit tests'
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '$(System.DefaultWorkingDirectory)/test-report.xml'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    condition: in(variables['Agent.JobStatus'], 'Succeeded')
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

  - task: ArchiveFiles@2
    displayName: 'Archive sources'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: CopyFiles@2
    displayName: 'Copy ARM templates'
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/Templates'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop' 

  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis'
    inputs:
      SonarCloud: 'SonarCloud connection 1'
      organization: '$(SonarOrganization)'
      scannerMode: 'MSBuild'
      projectKey: '$(SONAR_PROJECT_KEY)'
      projectName: '$(SonarProjectName)'
      projectVersion: '$(Build.BuildNumber)'
      extraProperties: |
       sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.opencover.xml
       sonar.exclusions=**/wwwroot/lib/**/*
  - script: |
      reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines
    displayName: 'Create code coverage report'

  - task: SonarCloudAnalyze@1
    displayName: 'Run SonarCloud code analysis'

  - task: SonarCloudPublish@1
    displayName: 'Publish SonarCloud quality gate results'